### ISSUE TITLE
Custom styles do not apply.

### ISSUE THREAD

**Issue by yehuuu6** [jantinnerezo/livewire-alert#154]
```php
$this->alert('success', 'Comment created.', [
    'customClass' => [
        'title' => 'bg-blue-500',
    ]
]);
```

I can only find this tailwind class that is working, of course I did not try everything, but text-blue-500 does not work for title. Also could not change any other styles for other components like container, loader, footer etc.

The only classname that is working rn is bg-blue-500 in my tests. I can not configure the style of this notification.

(I have tried disabling the toast, I can not customize the non-toast notifications aswell.)

**Comment by yehuuu6** [comment]
Fixed it by adding;

```php
$this->alert('success', 'Comment created.', [
    'iconColor' => 'white',
    'customClass' => [
        'popup' => 'colored-toast',
    ]
]);
```

And of course add the styling to your app.css for .colored-toast class. (Styling taken from directly sweetaler2 examples)

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
    body * {
        @apply scrollbar-thin scrollbar-thumb-blue-300 scrollbar-track-gray-200;
    }
}

.colored-toast.swal2-icon-success {
    background-color: #a5dc86 !important;
}

.colored-toast.swal2-icon-error {
    background-color: #f27474 !important;
}

.colored-toast.swal2-icon-warning {
    background-color: #f8bb86 !important;
}

.colored-toast.swal2-icon-info {
    background-color: #3fc3ee !important;
}

.colored-toast.swal2-icon-question {
    background-color: #87adbd !important;
}

.colored-toast .swal2-title {
    color: white;
}

.colored-toast .swal2-close {
    color: white;
}

.colored-toast .swal2-html-container {
    color: white;
}
```
